# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('과목번호', models.IntegerField(primary_key=True, serialize=False)),
                ('과목명', models.CharField(max_length=200)),
                ('학점', models.IntegerField(default=0)),
                ('is_전공', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('성적', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='성적')),
                ('수강학년', models.IntegerField(default=0)),
                ('수강학기', models.IntegerField(default=0)),
                ('과목', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('학번', models.IntegerField(primary_key=True, serialize=False)),
                ('이름', models.CharField(max_length=200)),
                ('학년', models.IntegerField(default=0)),
                ('전화번호', models.CharField(max_length=200)),
                ('이메일', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='enrol',
            name='학생',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Student'),
        ),
    ]
